version: '3'
services:
  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=weatherdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data